server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: http://order-service:8081
            predicates:
              - Path=/orders,/orders/**
          - id: inventory-service
            uri: http://inventory-service:8082
            predicates:
              - Path=/inventory,/inventory/**
          - id: billing-service
            uri: http://billing-service:8083
            predicates:
              - Path=/billing,/billing/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
